(defproject autodoc-client "0.9.0-SNAPSHOT"
  :description "Tools to retrieve and manipulate the index data generated by autodoc"
  :url "http://github.com/tomfaulhaber/autodoc-client"
  :dependencies [[org.clojure/clojure "1.2.0"]
                 [org.clojure/clojure-contrib "1.2.0"]
                 [clj-http "0.1.1"]
                 [enlive "1.0.0-SNAPSHOT"]]
  :dev-dependencies [[swank-clojure "1.2.1"]])
